# Generated by Django 5.2.8 on 2025-12-29 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='物料编码')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='物料分类')),
                ('unit', models.CharField(blank=True, default='', max_length=20, verbose_name='单位')),
                ('supplier', models.CharField(blank=True, default='', max_length=100, verbose_name='供应商')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('desc', models.TextField(blank=True, default='', verbose_name='特征描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('role_code', models.CharField(max_length=20, unique=True, verbose_name='角色编码')),
                ('desc', models.TextField(blank=True, verbose_name='角色描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'erp_role',
            },
        ),
        migrations.CreateModel(
            name='ERPUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myerpapp.role', verbose_name='所属角色')),
            ],
            options={
                'verbose_name': 'ERP用户',
                'verbose_name_plural': 'ERP用户',
            },
        ),
        migrations.CreateModel(
            name='PermissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(choices=[('material', '物料表单'), ('order', '订单表单'), ('erp_user', 'ERP用户表单'), ('product', '产品表单'), ('role', '角色表单'), ('contract', '合同表单')], max_length=20, verbose_name='表单名称')),
                ('action', models.CharField(choices=[('view', '查看'), ('add', '新增'), ('edit', '修改'), ('delete', '删除'), ('export', '导出')], max_length=10, verbose_name='操作权限')),
                ('name', models.CharField(blank=True, editable=False, max_length=100, verbose_name='权限名称')),
                ('code', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='权限编码')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='权限描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myerpapp.role', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': '权限配置',
                'verbose_name_plural': '权限配置',
                'unique_together': {('role', 'form_name', 'action')},
            },
        ),
        migrations.CreateModel(
            name='RoleFormPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(choices=[('material', '物料表单'), ('order', '订单表单'), ('erp_user', 'ERP用户表单'), ('product', '产品表单'), ('role', '角色表单'), ('contract', '合同表单')], max_length=20, verbose_name='表单名称')),
                ('action', models.CharField(choices=[('view', '查看'), ('add', '新增'), ('edit', '修改'), ('delete', '删除'), ('export', '导出')], max_length=10, verbose_name='操作权限')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myerpapp.role', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': '角色表单权限',
                'verbose_name_plural': '角色表单权限',
                'db_table': 'erp_role_form_permission',
                'unique_together': {('role', 'form_name', 'action')},
            },
        ),
    ]
