# Generated by Django A.B.C on YYYY-MM-DD HH:MM
from django.db import migrations
from django.db.models import F


def init_default_data(apps, schema_editor):
    """迁移中初始化默认数据（表创建完成后执行）"""
    # 延迟加载模型
    Role = apps.get_model('myerpapp', 'Role')
    ERPUser = apps.get_model('myerpapp', 'ERPUser')
    RoleFormPermission = apps.get_model('myerpapp', 'RoleFormPermission')
    PermissionConfig = apps.get_model('myerpapp', 'PermissionConfig')

    # 全局枚举（与models.py保持一致）
    FORM_CHOICES = [
        ('material', '物料表单'),
        ('order', '订单表单'),
        ('erp_user', 'ERP用户表单'),
        ('product', '产品表单'),
        ('role', '角色表单'),
        ('contract', '合同表单')
    ]
    ACTION_CHOICES = [
        ('view', '查看'),
        ('add', '新增'),
        ('edit', '修改'),
        ('delete', '删除'),
        ('export', '导出')
    ]

    # 1. 创建管理员角色
    admin_role, created = Role.objects.get_or_create(
        role_code='admin',
        defaults={
            'role_name': '系统管理员',
            'desc': '拥有所有表单的所有权限'
        }
    )
    print("✅ 系统管理员角色创建成功" if created else "ℹ️ 管理员角色已存在")

    # 2. 创建管理员用户
    admin_user, created = ERPUser.objects.get_or_create(
        username='admin',
        defaults={
            'password': '123456',
            'role': admin_role,
            'is_active': True
        }
    )
    print("✅ 默认管理员创建成功：admin/123456" if created else "ℹ️ 管理员用户已存在")

    # 3. 初始化权限配置
    # 3.1 旧版RoleFormPermission
    for form_value, _ in FORM_CHOICES:
        for action_value, _ in ACTION_CHOICES:
            RoleFormPermission.objects.get_or_create(
                role=admin_role,
                form_name=form_value,
                action=action_value,
                defaults={'is_active': True}
            )

    # 3.2 新版PermissionConfig
    for form_value, _ in FORM_CHOICES:
        for action_value, _ in ACTION_CHOICES:
            # 自动生成name/code（模拟models.py中的save逻辑）
            form_name_cn = dict(FORM_CHOICES).get(form_value, form_value)
            action_cn = dict(ACTION_CHOICES).get(action_value, action_value)
            name = f"{admin_role.role_name}-{form_name_cn}-{action_cn}"
            code = f"{admin_role.role_code}_{form_value}_{action_value}".lower()

            PermissionConfig.objects.get_or_create(
                role=admin_role,
                form_name=form_value,
                action=action_value,
                defaults={
                    'name': name,
                    'code': code,
                    'desc': f'管理员{action_cn}{form_name_cn}权限'
                }
            )
    print("✅ 管理员权限配置完成")


def reverse_func(apps, schema_editor):
    """回滚逻辑（可选，删除默认数据）"""
    Role = apps.get_model('myerpapp', 'Role')
    ERPUser = apps.get_model('myerpapp', 'ERPUser')
    RoleFormPermission = apps.get_model('myerpapp', 'RoleFormPermission')
    PermissionConfig = apps.get_model('myerpapp', 'PermissionConfig')

    # 删除管理员权限
    admin_role = Role.objects.filter(role_code='admin').first()
    if admin_role:
        RoleFormPermission.objects.filter(role=admin_role).delete()
        PermissionConfig.objects.filter(role=admin_role).delete()
        # 保留管理员用户/角色，避免误删
        print("ℹ️ 已回滚管理员权限配置")


class Migration(migrations.Migration):
    dependencies = [
        ('myerpapp', '0001_initial_tables'),  # 依赖基础表结构迁移
    ]

    operations = [
        migrations.RunPython(init_default_data, reverse_func),
    ]