# Generated by Django 5.2.8 on 2025-12-29 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myerpapp', '0003_drop_role_form_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionconfig',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='myerpapp.role', verbose_name='关联角色'),
        ),
    ]
