# Generated by Django 5.2.8 on 2025-12-31 12:21

import django.db.models.deletion
import myerpapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myerpapp', '0004_alter_permissionconfig_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myerpapp.erpuser', verbose_name='创建人'),
        ),
        migrations.AlterModelTable(
            name='material',
            table='erp_material',
        ),
        migrations.AlterModelTable(
            name='permissionconfig',
            table='erp_permission_config',
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=myerpapp.models.material_file_path, verbose_name='附件文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(blank=True, default='', max_length=50, verbose_name='文件类型')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_files', to='myerpapp.material', verbose_name='关联物料')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myerpapp.erpuser', verbose_name='上传人')),
            ],
            options={
                'verbose_name': '物料附件',
                'verbose_name_plural': '物料附件',
                'db_table': 'erp_material_file',
                'ordering': ['-upload_time'],
            },
        ),
    ]
