# Generated by Django 5.2.8 on 2025-12-31 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myerpapp', '0005_material_creator_alter_material_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': '物料', 'verbose_name_plural': '物料'},
        ),
        migrations.AlterModelOptions(
            name='materialfile',
            options={'verbose_name': '物料文件', 'verbose_name_plural': '物料文件'},
        ),
        migrations.RemoveField(
            model_name='materialfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='materialfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='materialfile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='materialfile',
            name='original_filename',
        ),
        migrations.AddField(
            model_name='material',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='materialfile',
            name='file_name',
            field=models.CharField(default='未命名文件', max_length=255, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='materialfile',
            name='file_path',
            field=models.CharField(default='', max_length=500, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='物料分类'),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='物料编码'),
        ),
        migrations.AlterField(
            model_name='material',
            name='creator',
            field=models.CharField(default='admin', max_length=100, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='material',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='特征描述'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, verbose_name='物料名称'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='myerpapp.material', verbose_name='关联物料'),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='uploader',
            field=models.CharField(default='未知用户', max_length=100, verbose_name='上传人'),
        ),
        migrations.AlterModelTable(
            name='material',
            table=None,
        ),
        migrations.AlterModelTable(
            name='materialfile',
            table=None,
        ),
    ]
