# Generated by Django 5.2.8 on 2025-12-31 15:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myerpapp', '0006_alter_material_options_alter_materialfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialfile',
            options={'verbose_name': '物料附件', 'verbose_name_plural': '物料附件'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='creator',
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='物料分类'),
        ),
        migrations.AlterField(
            model_name='material',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='物料编码'),
        ),
        migrations.AlterField(
            model_name='material',
            name='desc',
            field=models.TextField(default='', verbose_name='特征描述'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100, verbose_name='物料名称'),
        ),
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.CharField(default='', max_length=100, verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='', max_length=20, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='file_path',
            field=models.CharField(max_length=500, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myerpapp.material', verbose_name='关联物料'),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='uploader',
            field=models.CharField(max_length=100, verbose_name='上传人'),
        ),
        migrations.AlterModelTable(
            name='material',
            table='myerpapp_material',
        ),
    ]
