# Generated by Django 5.2.8 on 2025-12-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myerpapp', '0007_alter_materialfile_options_remove_material_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='materialfile',
            name='uploader',
        ),
        migrations.AddField(
            model_name='materialfile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='文件原始名称'),
        ),
        migrations.AddField(
            model_name='materialfile',
            name='size',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='文件大小（字节）'),
        ),
        migrations.AlterField(
            model_name='materialfile',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterModelTable(
            name='materialfile',
            table='myerpapp_materialfile',
        ),
    ]
