# Generated by Django 5.2.8 on 2026-01-01 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myerpapp', '0008_remove_materialfile_file_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='流程描述')),
                ('status', models.CharField(choices=[('active', '已启用'), ('inactive', '未启用')], default='inactive', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '审批流程',
                'verbose_name_plural': '审批流程',
            },
        ),
        migrations.CreateModel(
            name='ProcessNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('type', models.CharField(choices=[('start', '开始节点'), ('approve', '审批节点'), ('end', '结束节点')], max_length=20, verbose_name='节点类型')),
                ('approvers', models.JSONField(default=list, verbose_name='审批人ID列表')),
                ('timeout', models.CharField(blank=True, max_length=50, null=True, verbose_name='超时设置')),
                ('sort', models.IntegerField(default=0, verbose_name='排序值')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='myerpapp.process', verbose_name='所属流程')),
            ],
            options={
                'verbose_name': '流程节点',
                'verbose_name_plural': '流程节点',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='ProcessEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='myerpapp.process', verbose_name='所属流程')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='myerpapp.processnode', verbose_name='源节点')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='myerpapp.processnode', verbose_name='目标节点')),
            ],
            options={
                'verbose_name': '流程连线',
                'verbose_name_plural': '流程连线',
            },
        ),
    ]
