# Generated by Django 5.2.8 on 2026-01-03 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myerpapp', '0009_process_processnode_processedge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='流程编码')),
                ('desc', models.TextField(blank=True, verbose_name='流程描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '审批流程',
                'verbose_name_plural': '审批流程',
            },
        ),
        migrations.RemoveField(
            model_name='processedge',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processnode',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processedge',
            name='source_node',
        ),
        migrations.RemoveField(
            model_name='processedge',
            name='target_node',
        ),
        migrations.CreateModel(
            name='ApprovalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('start', '开始节点'), ('approver', '审批节点'), ('condition', '条件节点'), ('end', '结束节点')], max_length=20, verbose_name='节点类型')),
                ('approver_config', models.JSONField(blank=True, null=True, verbose_name='审批人配置')),
                ('next_nodes', models.JSONField(blank=True, null=True, verbose_name='流转规则')),
                ('sort', models.IntegerField(default=0, verbose_name='节点排序')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='myerpapp.approvalflow', verbose_name='所属流程')),
            ],
            options={
                'verbose_name': '审批节点',
                'verbose_name_plural': '审批节点',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=100, verbose_name='业务单据ID')),
                ('business_type', models.CharField(max_length=50, verbose_name='业务类型')),
                ('status', models.CharField(choices=[('running', '审批中'), ('approved', '已通过'), ('rejected', '已驳回')], max_length=20, verbose_name='审批状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myerpapp.approvalflow', verbose_name='关联流程')),
                ('current_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myerpapp.approvalnode', verbose_name='当前节点')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', '同意'), ('reject', '驳回'), ('transfer', '转审')], max_length=20, verbose_name='操作类型')),
                ('comment', models.TextField(blank=True, verbose_name='审批意见')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='myerpapp.approvalinstance', verbose_name='审批实例')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myerpapp.approvalnode', verbose_name='审批节点')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录',
            },
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.DeleteModel(
            name='ProcessEdge',
        ),
        migrations.DeleteModel(
            name='ProcessNode',
        ),
    ]
